import './post-catalogs-side-column/post-catalogs-side-column.widget';
import './post-catalogs-side-column/post-catalogs-side-column.config';
import './post-items-list/post-items-list.widget';
import './post-items-list/post-items-list.config';
import './post-items-list/post-items-list-by-catalog.config';
import './navigation/navigation.widget';
import './navigation/navigation.config';
import './logo/logo.widget';
import './logo/logo.config';
